- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always

- op: replace
  path: /spec/template/spec/containers/0/image
  value:  hobbes.azurecr.io/hobbes-azuredevops:latest

- op: replace
  path: /spec/replicas
  value: 3