apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - odata-deployment.yaml
  - prod_patches/odata-hpa.yaml
  
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: odata
    path: prod_patches/odata-prod.yaml