apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuredevops
  template:
    metadata:
      labels:
        app: azuredevops
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        imagePullPolicy: Never
        image: azuredevops
        name: azuredevops
        resources: {}
        env:
          - name: MAX_LOG_LENGTH
            value: "50000000"
      restartPolicy: Always
      imagePullSecrets:
      - name: acr-secret
status: {}