apiVersion: apps/v1
kind: Deployment
metadata:
  name: odata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odata
  template:
    metadata:
      labels:
        app: odata
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        imagePullPolicy: Never
        image: odata
        name: odata
        resources: {}
        env:
          - name: MAX_LOG_LENGTH
            value: "50000000"
      restartPolicy: Always
      imagePullSecrets:
      - name: acr-secret
status: {}